export const ADD_TOAST = "add_toast"
export const DISMISS_TOAST = "dismiss_toast"
export const FETCH_TOKEN = "fetch_token"
export const DELETE_TOKEN = "delete_token"
export const CREATE_USER = "create_user"