defmodule TwoPianos.LobbyChannel do
  use TwoPianos.Web, :channel
  alias TwoPianos.Presence

  # WHAT NEEDS TO HAPPEN

  # Rooms contain 2 pianos. They can be 1 of 2 types...
  # 1) Protected - Generated by someone who has a specific person they want to match with. Room will have an associate code.
  # 2) Random    - Generated by someone who is interested in playing with a stranger.

  # Need a way to see all currently existing rooms and a way for a user to join an existing room

  def join("two_pianos:lobby", _anon_variable, socket) do
    {:ok, socket}
  end

  def handle_in("create_room", _message, socket) do
    # Generate unique room ID and code,
    # Spawn ProtectedRoom, passing ID and code
    # Store ID, code and room handler value (PID maybe?) somewhere that it can be queried by the RoomFiller
    # Push room id and room code back to user -> they will join the room's specific channel, will be able to see the code, and will have a piano to mess around with
    {:noreply, socket}
  end

  def handle_in("random_room", _message, socket) do
    # Generate unique room ID,
    # Spawn RandomRoom, passing ID
    # Store ID and
    {:noreply, socket}
  end

  def handle_in("join_room", _message, socket) do
    # Use
    {:noreply, socket}
  end

end
